### ISSUE TITLE
Prometheus Targets Regex Error

### ISSUE THREAD

**Issue by zsnmwy** [gocrane/helm-charts#66]
<img width="688" alt="image" src="https://user-images.githubusercontent.com/35299017/177934637-391c41a5-055f-40c6-bfca-768de3f1292a.png">

https://github.com/gocrane/helm-charts/blob/b2917aa72ca5718085373398271a85b4fd65ad94/integration/prometheus/override_values.yaml#L73-L77

**Comment by yanhuan0802** [comment]
This bug seems to have been fixed.  #73
