### ISSUE TITLE
Some questions about scheduler chart repo version

### ISSUE THREAD

**Issue by yanhuan0802** [gocrane/helm-charts#71]
@qmhu , hello
1. I would like to know why scheduler chart appVersion is 0.2.0 instead of 0.1.23 or 0.0.23, what does 0.2.0 mean? I think the appVersion should be the same as the version of the main project, what do you think?
2. the last commit did not modify the chartVersion, which caused the CI process to report an error, the last modification was not applied, I can try to fix it.

**Comment by xieydd** [comment]
@qmhu We can matainer a version matrix.

**Comment by qmhu** [comment]
@yanhuan0802 Currently we don't see requirement for crane-scheduler to maintain the consistence between chart version and image tags, but crane has. So you can just raise the chart version for crane-scheduler.

I think it's a config mistake so the version might be v0.2.1

**Comment by yanhuan0802** [comment]
#72
