### ISSUE TITLE
there is some error in install crane to other namespace

### ISSUE THREAD

**Issue by zj452008181** [gocrane/helm-charts#78]
version:
crane 0.7.0
k8s:1.22.10
helm chart version:0.7.0

i install crane to kube-system namespace,the apiserver and webhook will get errors,i found wenhook certs only cn=crane-system,and api server helm template have static namespace。
`apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
  labels:
    {{- include "crane.labels" . | nindent 4 }}
spec:
  service:
    name: metric-adapter
    namespace: crane-system
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100`

**Comment by qmhu** [comment]
Currently crane don't support installed in other namespace.
