### ISSUE TITLE
My k8s version is 1.14.1, is there a suitable crane for this version?

### ISSUE THREAD

**Issue by xinsir88** [gocrane/helm-charts#84]
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/44859018/199423725-43b78563-fa70-4e4b-a98a-863951747d3f.png">
My k8s version is 1.14.1, is there a suitable crane for this version?

**Comment by qmhu** [comment]
yes, but i should be helped from our guideline. please join our wechat group to go to detail.
