### ISSUE TITLE
如何使用自有Prometheus+Kafka搭建Crane？

### ISSUE THREAD

**Issue by xinsir88** [gocrane/helm-charts#85]
老师，您好:
        如何使用自有Prometheus+Kafka搭建Crane？我修改了Grafana和Prometheus的连接地址，但是现在Crane控制台无法获取到Grafana。并且使用 [域名]:[port]/grafana无法正确跳转的我们Grafana页面。请知道。

**Comment by qmhu** [comment]
在这里讨论：https://github.com/gocrane/crane/issues/606
